package com.example.Microservice_OAD.model;

import javax.persistence.*;

// create table TODOUSER.Usuario (
//     IdUsuario number GENERATED by DEFAULT as IDENTITY,
//     Nombre varchar2(20),
//     Apellido varchar2(20),
//     Correo varchar2(50),
//     Contraseña varchar2(20),
//     Rol varchar(20),
//     TelegramId int,
//     IsActive number(1),
//     primary key (IdUsuario)
// );

@Entity
@Table(name = "Usuario", schema = "TODOUSER")
public class Usuario {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "IDUSUARIO")
    private int IdUsuario;

    @Column(name = "NOMBRE")
    private String nombre;

    @Column(name = "APELLIDO")
    private String apellido;

    @Column(name = "CORREO")
    private String correo;

    @Column(name = "CONTRASEÑA")
    private String contraseña;

    @Column(name = "ROL")
    private String rol;

    @Column(name = "TELEGRAMID")
    private Long telegramId;

    @Column(name = "ISACTIVE")
    private boolean isActive;

    public Usuario() {

    }

    public Usuario(int IdUsuario, String nombre, String apellido, String correo, String contraseña, String rol, Long telegramId, boolean isActive ) {
        this.IdUsuario = IdUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.correo = correo;
        this.contraseña = contraseña;
        this.rol = rol;
        this.telegramId = telegramId;
        this.isActive = isActive;
    }

    public int getIdUsuario(){
        return IdUsuario;
    }

    public void setIdUsuario(int IdUsuario){
        this.IdUsuario = IdUsuario;
    }

    public String getNombre(){
        return nombre;
    }

    public void setNombre(String nombre){
        this.nombre = nombre;
    }

    public String getApellido(){
        return apellido;
    }

    public void setApellido(String apellido){
        this.apellido = apellido;
    }

    public String getCorreo(){
        return correo;
    }

    public void setCorreo(String correo){
        this.correo = correo;
    }

    public String getContraseña(){
        return contraseña;
    }

    public void setContraseña(String contraseña){
        this.contraseña = contraseña;
    }

    public String getRol(){
        return rol;
    }

    public void setRol(String rol){
        this.rol = rol;
    }

    public Long getTelegramId(){
        return telegramId;
    }

    public void setTelegramId(Long telegramId){
        this.telegramId = telegramId;
    }

    public boolean geIsActive(){
        return isActive;
    }

    public void setIsActive(boolean isActive){
        this.isActive = isActive;
    }

}
