# This is a basic workflow to help you get started with Actions

name: Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "jorge-nunez" ]
  pull_request:
    branches: [ "main", "jorge-nunez" ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GOOGLE_JAVA_FORMAT: false;
          VALIDATE_JAVA: true;
          JAVA_FILE_NAME: OracleChatBot-Equipo6/checkstyle.xml;
          VALIDATE_NATURAL_LANGUAGE: false;
          VALIDATE_BASH: false;
          VALIDATE_GITLEAKS: false;
          VALIDATE_JSCPD: false;
          VALIDATE_MARKDOWN: false;
